### PR TITLE
Update command

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards KPI Monitoring.

Update the command in order to better structure the project.
Remove the `alert` and `opsgenie` package which where previously moved under `service/collector/`

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
Diff is a bit bad to read.

This seems fine code wise.

**Comment by TheoBrigitte** [comment]
> Diff is a bit bad to read.

Using split diff here make sense for easier reading as most of the `main.go` file changed.

**Comment by JosephSalisbury** [comment]
@TheoBrigitte still working on this? i have a pending review that i don't care much about :D

**Comment by TheoBrigitte** [comment]
I'm not working on that, no idea what I did there. Closing

**Pull request closed without merging**
